// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6RrUCGYtVhA10ld4LSVt_sVWQ6wIWyCw',
    appId: '1:786221558289:web:b92d8b63b3385849c51fb0',
    messagingSenderId: '786221558289',
    projectId: 'rehapp-dc805',
    authDomain: 'rehapp-dc805.firebaseapp.com',
    storageBucket: 'rehapp-dc805.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYqxp6OOUaNk9ewdzZ9X3DbucQrapdNDI',
    appId: '1:786221558289:android:25eb545ca3852b25c51fb0',
    messagingSenderId: '786221558289',
    projectId: 'rehapp-dc805',
    storageBucket: 'rehapp-dc805.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDyhobjEq8F2ZZKYqxMsZctZyI1EazxdPE',
    appId: '1:786221558289:ios:0a89203adb74f21bc51fb0',
    messagingSenderId: '786221558289',
    projectId: 'rehapp-dc805',
    storageBucket: 'rehapp-dc805.appspot.com',
    iosClientId: '786221558289-fp5okiduq6uprs7vg8ofe5nv3dq6658c.apps.googleusercontent.com',
    iosBundleId: 'com.example.rehapp',
  );
}
